Update meta.yaml for new package version from CRAN
conda-forge/r-w4mrutils-feedstock pull request #2
Opened 2023-09-11 14:13 UTC by melpetera

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2023-09-11 14:16 UTC, melpetera commented
@conda-forge-admin, please rerender

2023-09-11 15:03 UTC, melpetera commented
@conda-forge/r  could you review my PR please?

2023-09-11 15:08 UTC, melpetera commented
@conda-forge-admin, please ping conda-forge/r

2023-09-11 15:08 UTC, melpetera commented
Could you review my PR please?

2023-09-11 20:45 UTC, mfansler requested changes
Thanks for submitting this PR. There are some changes suggested.

2023-09-11 20:45 UTC, mfansler commented on recipe/meta.yaml
> +  url: https://cran.r-project.org/src/contrib/W4MRUtils_{{ version }}.tar.gz
Use Jinja variable and pre-emptively include archive searching:

```suggestion
  url:
    - {{ cran_mirror }}/src/contrib/W4MRUtils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/W4MRUtils/W4MRUtils_{{ version }}.tar.gz
```

2023-09-11 20:45 UTC, mfansler commented on recipe/LICENSE.md
This isn't necessary. Instead, the `license_file` should be set to pick up the shared copy from R, i.e.,

```
license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3
```

I.e., delete this file and make this change in `meta.yaml`.

2023-09-13 08:32 UTC, melpetera commented on recipe/LICENSE.md
Done in 96c47bf31c2d1498e6ad1494ef106f0feae9e4aa and ebf3af55cf885c42a433a43d257c702b49ccb1c6

Thank you for the review.

2023-09-13 08:55 UTC, melpetera commented
Thank you for the review.
I hope I did the right modifications.

2023-09-14 04:58 UTC, mfansler approved these changes

2023-09-14 05:00 UTC, merged